[workspace]
members = [
    "ruleco-actor",
    "ruleco-core",
    "ruleco-coordinator",
    "ruleco-legacy",
]
resolver = "3"

[workspace.package]
version = "0.1.0"
authors = ["BB"]
description = "Rust implementation of LECO, the Laboratory Experimental Control Protocol"
documentation = "https://github.com/BenediktBurger/ruleco"
edition = "2021"
